// Gera pt.html a partir do index.html trocando só os textos visíveis (EN -> PT).
// Estrutura/CSS/JS ficam idênticos. Rode: node generate-pt.mjs
import fs from "node:fs";

let html = fs.readFileSync("index.html", "utf8");

const pairs = [
  // ---------- head / nav ----------
  ['<html lang="en">', '<html lang="pt-BR">'],
  ["Crisla Pott · Senior Product Manager", "Crisla Pott · Product Manager Sênior"],
  ["Senior PM with 8 years at Rappi. Backoffice products, real-time monitoring, post-order UX across 9 LATAM countries.",
   "PM sênior com 8 anos de Rappi. Produtos de backoffice, monitoramento em tempo real e UX de pós-pedido em 9 países da América Latina."],
  ['href="pt.html">PT</a>', 'href="index.html">EN</a>'],
  [">Work</a>", ">Trabalho</a>"],
  [">Skills</a>", ">Habilidades</a>"],
  [">Career</a>", ">Carreira</a>"],
  [">Education</a>", ">Formação</a>"],
  [">Contact</a>", ">Contato</a>"],

  // ---------- hero ----------
  [">Senior Product Manager</div>", ">Product Manager Sênior</div>"],
  ["Backoffice &amp; Marketplace · LATAM &amp; Global", "Backoffice &amp; Marketplace · América Latina &amp; Global"],
  ["I build the systems that <strong>keep operations running</strong> — real-time monitoring platforms, backoffice tooling, and post-order UX that scale across markets and teams. Eight years at Rappi, shipping products used across <strong>9 countries in Latin America</strong>.",
   "Eu construo os sistemas que <strong>mantêm a operação de pé</strong>: plataformas de monitoramento em tempo real, ferramentas de backoffice e UX de pós-pedido que escalam entre mercados e times. Oito anos de Rappi, entregando produtos usados em <strong>9 países da América Latina</strong>."],
  ["I started in field ops and grew into full product ownership by building from scratch — connecting engineering, ops, and business around shared problems. I use AI tools as a core part of how I work, every day. I thrive where there's no playbook yet.",
   "Comecei na operação de campo e cresci até assumir produto de ponta a ponta, construindo do zero e conectando engenharia, operação e negócio em torno de problemas comuns. Uso ferramentas de IA como parte central do meu trabalho, todo dia. Me realizo onde ainda não existe manual."],
  [">See my work ↓</a>", ">Ver meu trabalho ↓</a>"],
  [">Open to new opportunities as of 2026</span>", ">Aberta a novas oportunidades a partir de 2026</span>"],

  // ---------- expertise / pillars ----------
  [">What I build</h2>", ">O que eu construo</h2>"],
  [">Backoffice products</h3>", ">Produtos de backoffice</h3>"],
  ["Tools that ops teams actually use — monitoring platforms, internal dashboards, incident response systems. Built for scale, not for demos.",
   "Ferramentas que os times de operação realmente usam: plataformas de monitoramento, dashboards internos, sistemas de resposta a incidentes. Feitas para escala, não para demo."],
  [">Post-order &amp; cancellations UX</h3>", ">UX de pós-pedido &amp; cancelamentos</h3>"],
  ["The flows that save orders, protect revenue, and keep customers. 1,700+ orders recovered per week across 9 countries.",
   "Os fluxos que salvam pedidos, protegem receita e retêm clientes. Mais de 1.700 pedidos recuperados por semana em 9 países."],
  [">Building with AI</h3>", ">Construir com IA</h3>"],
  ["I use Claude, ChatGPT, and Claude Code to build real things — from PRDs to full products like Hotzones, shipped end-to-end with AI as co-pilot.",
   "Uso Claude, ChatGPT e Claude Code pra construir coisas de verdade: de PRDs a produtos completos como o Hotzones, entregues de ponta a ponta com a IA como copiloto."],

  // ---------- case section ----------
  [">Case studies</div>", ">Estudos de caso</div>"],
  [">Selected work</h2>", ">Trabalhos selecionados</h2>"],
  ["Eight projects that represent the range of what I build — from zero-to-one monitoring platforms to consumer UX redesigns, evidence microservices, geospatial MVPs, fraud detection systems, operational automation tools, and a collaborative music app built end-to-end with AI.",
   "Oito projetos que mostram a amplitude do que eu construo: de plataformas de monitoramento do zero a redesenhos de UX de consumo, microsserviços de evidência, MVPs geoespaciais, sistemas de detecção de fraude, ferramentas de automação operacional e um app de playlist colaborativa feito de ponta a ponta com IA."],

  // ---------- case 08 playlist da galera ----------
  ["02 · Personal project · 2026", "02 · Projeto pessoal · 2026"],
  [">Playlist da Galera — Collaborative Party Playlists</div>", ">Playlist da Galera — Playlists Colaborativas de Rolê</div>"],
  ["Built with AI · No login · Live demo ↗", "Feito com IA · Sem login · Demo ao vivo ↗"],
  ["Every hangout has the same fight: whoever plugs in their phone owns the music, and one person's taste floods the whole night. A shared playlist never quite feels like <em>everyone's</em>.",
   "Todo rolê tem a mesma treta: quem pluga o celular manda na música, e o gosto de uma pessoa domina a noite inteira. Uma playlist compartilhada nunca parece ser <em>de todo mundo</em>."],
  ["A web app where everyone drops the songs they like — by pasting a public Spotify or YouTube playlist, or just searching, <strong>with no login</strong> — and the app blends them into a single set with two rules: <strong>fairness</strong> (nobody monopolizes; equal space per person) and <strong>flow</strong> (an energy arc that starts calm and builds to the peak of the night, like a DJ). It plays right inside the app — cast to a TV through the clips — or exports to Spotify.",
   "Um app web onde todo mundo joga as músicas que curte — colando uma playlist pública do Spotify ou do YouTube, ou só buscando, <strong>sem login</strong> — e o app mistura tudo num set só, com duas regras: <strong>justiça</strong> (ninguém monopoliza; cada pessoa tem o mesmo espaço) e <strong>fluxo</strong> (uma curva de energia que começa calma e sobe até o pico da noite, igual DJ). Dá pra tocar dentro do próprio app — jogar na TV pelos clipes — ou exportar pro Spotify."],
  ['<strong>Blend:</strong> dedupes shared songs into "anchors", gives every person an equal quota, and orders tracks along an exponential energy arc toward the end-of-night anthems. <strong>Vibe:</strong> reads each track\'s mood from Last.fm tags (Spotify retired audio-features). <strong>No login at scale:</strong> resolves songs and clips by reading public Spotify/YouTube pages directly, bypassing the platforms\' account and quota limits — so anyone can contribute and play without signing in. <strong>Stack:</strong> React · Vite · Supabase Edge Functions · Last.fm · Vercel.',
   '<strong>Blend:</strong> junta as músicas repetidas em "âncoras", dá a cada pessoa uma cota igual e ordena as faixas numa curva de energia exponencial rumo aos hinos do fim da festa. <strong>Vibe:</strong> lê o clima de cada faixa pelas tags do Last.fm (o Spotify aposentou os audio-features). <strong>Sem login em escala:</strong> resolve músicas e clipes lendo direto as páginas públicas do Spotify/YouTube, contornando os limites de conta e cota das plataformas — então qualquer um contribui e toca sem se cadastrar. <strong>Stack:</strong> React · Vite · Supabase Edge Functions · Last.fm · Vercel.'],
  ["Built end-to-end with Claude Code over a weekend — the blend algorithm, caching, the in-app player, PT/EN i18n, PWA, and deploy. I described the problem and made the product calls; the AI wrote the code while I tested and steered. The hardest part wasn't the code — it was deciding what to cut and designing the experience around what the platforms actually allow.",
   "Feito de ponta a ponta com o Claude Code num fim de semana — o algoritmo do blend, cache, o player embutido, i18n PT/EN, PWA e deploy. Eu descrevia o problema e tomava as decisões de produto; a IA escrevia o código enquanto eu testava e direcionava. A parte mais difícil não foi o código — foi decidir o que cortar e desenhar a experiência em cima do que as plataformas realmente permitem."],
  [">Concept to live, solo</div>", ">Do conceito ao ar, sozinha</div>"],
  [">To contribute, blend and play</div>", ">Pra contribuir, misturar e tocar</div>"],
  [">Bilingual · installable (PWA)</div>", ">Bilíngue · instalável (PWA)</div>"],
  [">1 weekend</div>", ">1 fim de semana</div>"],
  [">View live ↗</a>", ">Ver ao vivo ↗</a>"],
  [">Source on GitHub ↗</a>", ">Código no GitHub ↗</a>"],

  // repeated case labels
  [">The problem</div>", ">O problema</div>"],
  [">Approach</div>", ">Abordagem</div>"],
  [">Key decisions &amp; projects</div>", ">Decisões e projetos-chave</div>"],
  [">Key decisions</div>", ">Decisões-chave</div>"],
  [">My role</div>", ">Meu papel</div>"],
  [">What I learned</div>", ">O que aprendi</div>"],
  [">Impact</div>", ">Impacto</div>"],
  [">The context</div>", ">O contexto</div>"],
  [">What I built</div>", ">O que construí</div>"],
  [">What I'm building</div>", ">O que estou construindo</div>"],
  [">How it works</div>", ">Como funciona</div>"],
  [">How AI was used</div>", ">Como usei IA</div>"],
  [">Solution</div>", ">Solução</div>"],
  [">Tools</div>", ">Ferramentas</div>"],

  // ---------- case 01 OCC ----------
  ["06 · LATAM Marketplace · 2020–2023", "06 · Marketplace LATAM · 2020–2023"],
  ["Hundreds of thousands saved/yr · &lt;5 min response · 9 countries",
   "Centenas de milhares economizados/ano · resposta &lt;5 min · 9 países"],
  ["A large LATAM marketplace's operations were reactive by design. When a restaurant integration failed, a payment processor went down, or supply-demand imbalances spiked, the ops team discovered problems through <strong>customer complaints — not early detection</strong>. Incident response took over an hour. By then, hundreds of orders were affected and recovery costs were high. No centralized monitoring, no automation, no shared playbook across countries.",
   "A operação de um grande marketplace da América Latina era reativa por natureza. Quando uma integração de restaurante caía, um processador de pagamento saía do ar ou o desequilíbrio entre oferta e demanda disparava, o time descobria os problemas pelas <strong>reclamações dos clientes — não por detecção antecipada</strong>. Responder a um incidente levava mais de uma hora. A essa altura, centenas de pedidos já tinham sido afetados e o custo de recuperação era alto. Sem monitoramento centralizado, sem automação, sem um playbook comum entre os países."],
  ["Rather than patching individual problems, I focused on building infrastructure for proactive operations — a system that could detect anomalies in real time, route them to the right people, and resolve them before they escalated. <strong>Foundation before headcount</strong>: tooling first, then team structure.",
   "Em vez de remendar problemas isolados, foquei em construir infraestrutura para uma operação proativa — um sistema capaz de detectar anomalias em tempo real, direcioná-las às pessoas certas e resolvê-las antes de escalarem. <strong>Base antes de headcount</strong>: primeiro as ferramentas, depois a estrutura de time."],
  ["<strong>100+ real-time alerts</strong> built from scratch to detect anomalies across integrations, payments, restaurant performance, and supply — all verticals, 9 countries.",
   "<strong>Mais de 100 alertas em tempo real</strong> criados do zero para detectar anomalias em integrações, pagamentos, performance de restaurantes e oferta — todas as verticais, 9 países."],
  ["<strong>10+ automation bots</strong> for escalation, containment, and reporting — eliminating manual work that previously required dedicated headcount.",
   "<strong>Mais de 10 bots de automação</strong> para escalonamento, contenção e reporte — eliminando trabalho manual que antes exigia gente dedicada."],
  ["<strong>Holiday operations framework:</strong> Plug-and-play playbooks for peak days — pre-activating monitoring rules and response teams before incidents could occur.",
   "<strong>Framework de operação para feriados:</strong> playbooks plug-and-play para os dias de pico — pré-ativando regras de monitoramento e times de resposta antes que os incidentes acontecessem."],
  ["OCC strategy &amp; design · Backoffice product ownership · Process architecture &amp; documentation · Ops-to-tech translation · Cross-functional alignment · Team efficiency &amp; automation.",
   "Estratégia &amp; design do OCC · Ownership do produto de backoffice · Arquitetura &amp; documentação de processos · Tradução entre operação e tecnologia · Alinhamento cross-funcional · Eficiência de time &amp; automação."],
  ["Operational excellence is a product problem. The best interventions weren't process changes — they were systems that anticipated failures, automated response, and freed humans to focus on judgment-heavy exceptions. <em>You can't fix what you can't see.</em>",
   "Excelência operacional é um problema de produto. As melhores intervenções não foram mudanças de processo — foram sistemas que anteciparam falhas, automatizaram a resposta e liberaram as pessoas para focar nas exceções que exigem julgamento. <em>Você não conserta o que não consegue enxergar.</em>"],
  [">Incident response (from 1+ hour)</div>", ">Resposta a incidentes (de 1+ hora)</div>"],
  [">Annual savings via automation</div>", ">Economia anual via automação</div>"],
  [">Ops team size through automation</div>", ">Tamanho do time de ops via automação</div>"],
  [">Countries, all verticals</div>", ">Países, todas as verticais</div>"],
  [">Automation bots</span>", ">Bots de automação</span>"],
  [">Real-time alerting</span>", ">Alertas em tempo real</span>"],

  // ---------- case 02 cancellations ----------
  ["07 · LATAM Marketplace · 2026", "07 · Marketplace LATAM · 2026"],
  [">Cancellations UX Redesign</div>", ">Redesenho da UX de Cancelamentos</div>"],
  ["1,700+ orders saved per week · 9 countries", "Mais de 1.700 pedidos salvos por semana · 9 países"],
  ["When users wanted to cancel an order, the platform's flow went straight to confirmation — with no attempt to understand why or offer alternatives. Many cancellation intents were actually <strong>fixable problems</strong>: wrong address, preferred payment method unavailable, or order running late. The result was avoidable order loss, revenue impact, and a poor experience for users who would have stayed if given the right option at the right moment.",
   "Quando o usuário queria cancelar um pedido, o fluxo ia direto para a confirmação — sem tentar entender o porquê nem oferecer alternativas. Muitas intenções de cancelamento eram, na verdade, <strong>problemas resolvíveis</strong>: endereço errado, meio de pagamento preferido indisponível ou pedido atrasado. O resultado era perda de pedido evitável, impacto em receita e uma experiência ruim para quem teria ficado se recebesse a opção certa no momento certo."],
  ["Rather than accepting cancellation as the default outcome, the new flow <strong>intercepts the moment of intent</strong> and presents the user with relevant alternatives: change the delivery address, switch payment method, or accept a compensation to wait for a delayed order. Each option is shown conditionally — only when technically feasible and contextually relevant. The right option at the right moment creates retention; an irrelevant one creates friction.",
   "Em vez de aceitar o cancelamento como desfecho padrão, o novo fluxo <strong>intercepta o momento da intenção</strong> e apresenta alternativas relevantes: trocar o endereço de entrega, mudar o meio de pagamento ou aceitar uma compensação para esperar um pedido atrasado. Cada opção aparece de forma condicional — só quando é tecnicamente viável e faz sentido no contexto. A opção certa no momento certo gera retenção; uma irrelevante gera fricção."],
  ["<strong>Foundation first:</strong> modernized the underlying tech infrastructure with engineering before shipping any new UX — to avoid building on a fragile base that would limit future iterations.",
   "<strong>Base primeiro:</strong> modernizei a infraestrutura técnica com o time de engenharia antes de lançar qualquer UX nova — para não construir sobre uma base frágil que limitaria as próximas iterações."],
  ["<strong>Context-driven logic:</strong> designed rules for when to show each modification option based on order status, vertical, and cancellation reason — not a one-size-fits-all screen.",
   "<strong>Lógica orientada a contexto:</strong> desenhei regras de quando mostrar cada opção de modificação com base no status do pedido, na vertical e no motivo do cancelamento — nada de tela única para tudo."],
  ["<strong>Validated incrementally:</strong> launched delay compensation first as the simplest, most measurable intervention — generating proof of concept before investing in more complex modification flows.",
   "<strong>Validação incremental:</strong> lancei primeiro a compensação por atraso, a intervenção mais simples e mensurável — gerando prova de conceito antes de investir em fluxos de modificação mais complexos."],
  ["End-to-end PRD ownership · Problem framing &amp; solution scoping · Cross-functional alignment with engineering, design, data, and ops · A/B test design &amp; metric definition · Prioritization of rollout sequence across modification types.",
   "Ownership do PRD de ponta a ponta · Enquadramento do problema &amp; escopo da solução · Alinhamento cross-funcional com engenharia, design, dados e operação · Design de teste A/B &amp; definição de métricas · Priorização da ordem de rollout entre os tipos de modificação."],
  [">Orders saved per week via compensation offer</div>", ">Pedidos salvos por semana via oferta de compensação</div>"],
  [">Modification types: address, payment, delivery time</div>", ">Tipos de modificação: endereço, pagamento, horário</div>"],
  [">Countries across LATAM marketplace</div>", ">Países no marketplace LATAM</div>"],
  [">A/B testing</span>", ">Testes A/B</span>"],
  [">Related initiative — VoIP integration (Amazon Chime)</div>", ">Iniciativa relacionada — integração VoIP (Amazon Chime)</div>"],
  ['Led the scoping, spec, and delivery of a VoIP integration using Amazon Chime — covering permission flows and fallback logic for Android and iOS. <strong>Shipped to 80% of the user base</strong>. Designed to improve courier-user contactability, reduce "customer not home" cancellations, and decrease order not delivered complaints.',
   'Liderei o escopo, a especificação e a entrega de uma integração VoIP com o Amazon Chime — cobrindo fluxos de permissão e lógica de fallback para Android e iOS. <strong>Lançada para 80% da base de usuários</strong>. Feita para melhorar a comunicação entre entregador e cliente, reduzir cancelamentos por "cliente ausente" e diminuir as reclamações de pedido não entregue.'],

  // ---------- case 03 OND ----------
  ["04 · LATAM Marketplace · OCC umbrella", "04 · Marketplace LATAM · guarda-chuva do OCC"],
  [">Order Not Delivered — Delivery Evidence Microservice</div>", ">Pedido Não Entregue — Microsserviço de Evidência de Entrega</div>"],
  ["Tens of thousands saved/month · &lt;5 sec diagnosis · 9 countries",
   "Dezenas de milhares economizados/mês · diagnóstico em &lt;5 seg · 9 países"],
  ["Every day, thousands of customers opened support tickets claiming their order never arrived. The support team had no way to determine who was telling the truth — the driver claimed delivery, the customer claimed otherwise. With no evidence system, the default was to compensate the customer to avoid risk. This created two problems: <strong>significant monthly costs from unwarranted payouts</strong>, and no way to identify patterns of fraud or driver misconduct.",
   "Todo dia, milhares de clientes abriam tickets de suporte dizendo que o pedido nunca chegou. O suporte não tinha como saber quem falava a verdade — o entregador dizia ter entregue, o cliente dizia o contrário. Sem um sistema de evidências, o padrão era compensar o cliente para evitar risco. Isso criava dois problemas: <strong>custos mensais relevantes com pagamentos indevidos</strong> e nenhuma forma de identificar padrões de fraude ou má conduta de entregadores."],
  ["Rather than relying on manual case review, I led the development of a microservice that automatically analyzes the full order lifecycle at the moment a customer opens a ticket. The key insight: <strong>the evidence already existed in our systems</strong> — geolocation, photos, timestamps, chat history. We just needed to connect it and surface it at the right moment, before a human made a decision.",
   "Em vez de depender de revisão manual caso a caso, liderei o desenvolvimento de um microsserviço que analisa automaticamente todo o ciclo de vida do pedido no momento em que o cliente abre um ticket. O insight-chave: <strong>a evidência já existia nos nossos sistemas</strong> — geolocalização, fotos, timestamps, histórico de chat. Só precisávamos conectar tudo e trazer à tona no momento certo, antes de um humano decidir."],
  ["<strong>Prioritized 'order not delivered'</strong> over other defect types (damaged product, poor quality) because it had the highest user friction and the richest evidence trail.",
   "<strong>Priorizei 'pedido não entregue'</strong> frente a outros tipos de defeito (produto danificado, má qualidade) porque era o de maior fricção para o usuário e com a trilha de evidências mais rica."],
  ["<strong>Built the diagnosis at ticket-creation time</strong> — so the support agent received the evidence before making any decision, not as an afterthought.",
   "<strong>Montei o diagnóstico no momento de criação do ticket</strong> — para o agente de suporte receber a evidência antes de decidir, não depois."],
  ["<strong>Designed the output as a clear recommendation</strong> (evidence found / not found) rather than raw data — reducing cognitive load on support agents and standardizing decisions across teams.",
   "<strong>Desenhei o resultado como uma recomendação clara</strong> (evidência encontrada / não encontrada) em vez de dados crus — reduzindo a carga cognitiva dos agentes e padronizando as decisões entre times."],
  ["<strong>Launched first in smaller markets</strong> (Uruguay, Peru) as a controlled experiment. Initial results were below expectations, so we refined the model before rolling out to larger markets.",
   "<strong>Lancei primeiro em mercados menores</strong> (Uruguai, Peru) como experimento controlado. Os resultados iniciais ficaram abaixo do esperado, então refinamos o modelo antes de expandir para mercados maiores."],
  ["End-to-end problem framing &amp; solution scoping · Alignment with engineering and support teams · Prioritization rationale &amp; rollout sequencing · Experiment design &amp; post-launch iteration.",
   "Enquadramento do problema de ponta a ponta &amp; escopo da solução · Alinhamento com os times de engenharia e suporte · Racional de priorização &amp; sequência de rollout · Design de experimentos &amp; iteração pós-lançamento."],
  ["Beyond cost savings, the system created a consistent, data-driven standard for resolving disputed deliveries — reducing variability across support agents and countries. The evidence was always there. The product problem was surfacing it at the right moment.",
   "Além da economia, o sistema criou um padrão consistente e orientado a dados para resolver entregas contestadas — reduzindo a variação entre agentes e países. A evidência sempre esteve lá. O problema de produto era trazê-la à tona no momento certo."],
  [">Monthly reduction in unwarranted payouts</div>", ">Redução mensal em pagamentos indevidos</div>"],
  [">Time to generate delivery diagnosis</div>", ">Tempo para gerar o diagnóstico de entrega</div>"],
  [">Countries after full rollout</div>", ">Países após o rollout completo</div>"],
  [">Microservice architecture</span>", ">Arquitetura de microsserviços</span>"],
  [">Geolocation data</span>", ">Dados de geolocalização</span>"],
  [">Experiment design</span>", ">Design de experimentos</span>"],
  [">Support tooling</span>", ">Ferramentas de suporte</span>"],

  // ---------- case 04 hotzones ----------
  ["01 · Personal project · 2025", "01 · Projeto pessoal · 2025"],
  [">Hotzones MVP — Demand Forecasting Map</div>", ">Hotzones MVP — Mapa de Previsão de Demanda</div>"],
  ["Built solo · AI + AWS · Live demo ↗", "Feito sozinha · IA + AWS · Demo ao vivo ↗"],
  [">⚡ AI-assisted build</span>", ">⚡ Feito com apoio de IA</span>"],
  ["A personal project to prove a concept: a solo PM, using AI tools and cloud infrastructure, can ship a working geospatial product in a short iteration cycle — without a dedicated engineering team.",
   "Um projeto pessoal para provar um conceito: uma PM sozinha, usando ferramentas de IA e infraestrutura de nuvem, consegue entregar um produto geoespacial funcional num ciclo curto de iteração — sem um time de engenharia dedicado."],
  ["An interactive demand forecasting map for Bogotá that shows where food delivery orders concentrate across the city, in 30-minute time windows, for the next 3 days. Couriers see where demand is heading before it peaks. The same architecture scales to any city with order history.",
   "Um mapa interativo de previsão de demanda para Bogotá que mostra onde os pedidos de delivery se concentram na cidade, em janelas de 30 minutos, para os próximos 3 dias. Os entregadores veem para onde a demanda está indo antes do pico. A mesma arquitetura escala para qualquer cidade com histórico de pedidos."],
  ["<strong>Data:</strong> 30-day order history (lat/lng, timestamp). <strong>Spatial indexing:</strong> Uber H3 hexagonal grid at resolution 9 (~0.1 km² per cell). <strong>Forecast:</strong> Statistical demand profile per hex — fully explainable, no black box. <strong>Score:</strong> Percentile ranking (1–5) per time window, the same approach used by Uber and DoorDash. <strong>Exclusion:</strong> AK30 highway corridor removed via buffer geometry — a real operational barrier in Bogotá logistics. <strong>Stack:</strong> Python · pandas · h3 · shapely · Kepler.gl · AWS S3.",
   "<strong>Dados:</strong> 30 dias de histórico de pedidos (lat/lng, timestamp). <strong>Indexação espacial:</strong> grade hexagonal Uber H3 na resolução 9 (~0,1 km² por célula). <strong>Previsão:</strong> perfil estatístico de demanda por hexágono — totalmente explicável, sem caixa-preta. <strong>Score:</strong> ranking por percentil (1–5) por janela de tempo, a mesma abordagem usada por Uber e DoorDash. <strong>Exclusão:</strong> o corredor da rodovia AK30 é removido via geometria de buffer — uma barreira operacional real na logística de Bogotá. <strong>Stack:</strong> Python · pandas · h3 · shapely · Kepler.gl · AWS S3."],
  ["ChatGPT and Claude throughout the pipeline: architecture design, geospatial edge case debugging, Python scripts, scoring methodology validation. Claude Code for refactoring. From concept to live demo in a few weeks of part-time work.",
   "ChatGPT e Claude em todo o pipeline: design de arquitetura, debug de casos extremos geoespaciais, scripts em Python, validação da metodologia de score. Claude Code para refatoração. Do conceito à demo ao vivo em algumas semanas de trabalho part-time."],
  [">Forecast horizon</div>", ">Horizonte de previsão</div>"],
  [">Time granularity</div>", ">Granularidade de tempo</div>"],
  [">~0.1 km² per hex cell</div>", ">~0,1 km² por hexágono</div>"],
  [">View live demo ↗</a>", ">Ver demo ao vivo ↗</a>"],
  [">Time window</div>", ">Janela de tempo</div>"],
  [">HOTZONE SCORE</div>", ">PONTUAÇÃO HOTZONE</div>"],

  // ---------- case 05 fraud ----------
  ["03 · Personal project · In progress", "03 · Projeto pessoal · Em andamento"],
  [">AI Fraud-Detection — Driver Onboarding Pipeline</div>", ">Detecção de Fraude com IA — Pipeline de Cadastro de Entregadores</div>"],
  ["Self-initiated · Claude Code · Python · In progress", "Iniciativa própria · Claude Code · Python · Em andamento"],
  [">⚡ AI-native build · Claude Code</span>", ">⚡ Construção AI-native · Claude Code</span>"],
  ["Delivery platforms in LATAM face a growing threat during driver onboarding: <strong>synthetic-identity fraud</strong> — AI-generated profile photos reused across multiple fraudulent driver registrations under different documents. Manual fraud review is slow, inconsistent, and doesn't scale. No automated system existed to detect fraud rings across applications.",
   "As plataformas de delivery na América Latina enfrentam uma ameaça crescente no cadastro de entregadores: <strong>fraude de identidade sintética</strong> — fotos de perfil geradas por IA reutilizadas em vários cadastros fraudulentos sob documentos diferentes. A revisão manual de fraude é lenta, inconsistente e não escala. Não existia sistema automatizado para detectar quadrilhas de fraude entre os cadastros."],
  ["An end-to-end fraud-detection pipeline covering three layers of defense: <strong>document OCR cross-validation</strong> to catch inconsistencies between submitted documents; <strong>AI-generated image detection</strong> to flag synthetic profile photos; and <strong>facial-embedding deduplication</strong> to surface fraud rings — the same face registered under multiple different identities.",
   "Um pipeline de detecção de fraude de ponta a ponta com três camadas de defesa: <strong>validação cruzada de OCR dos documentos</strong> para pegar inconsistências entre os documentos enviados; <strong>detecção de imagens geradas por IA</strong> para sinalizar fotos de perfil sintéticas; e <strong>deduplicação por embedding facial</strong> para expor quadrilhas — o mesmo rosto cadastrado sob várias identidades diferentes."],
  ["<strong>Translated a manual process into automatable rules first</strong> — mapped every step the ops fraud-review team did manually, identified which decisions followed consistent logic, and converted those into business rules and risk-scoring thresholds before writing a single line of code.",
   "<strong>Primeiro traduzi um processo manual em regras automatizáveis</strong> — mapeei cada passo que o time de revisão de fraude fazia na mão, identifiquei quais decisões seguiam uma lógica consistente e as converti em regras de negócio e limiares de risk scoring antes de escrever uma única linha de código."],
  ["<strong>Modular architecture</strong> — each detection layer (OCR, image, face) operates independently, so the system can flag a case based on any single signal or a combination, and each module can be iterated without breaking the others.",
   "<strong>Arquitetura modular</strong> — cada camada de detecção (OCR, imagem, rosto) funciona de forma independente, então o sistema pode sinalizar um caso por um único sinal ou por uma combinação, e cada módulo evolui sem quebrar os outros."],
  ["<strong>Risk scoring output, not binary decisions</strong> — the system surfaces a risk score and evidence summary for human review, rather than auto-rejecting applications, keeping a human in the loop for edge cases.",
   "<strong>Saída em score de risco, não decisão binária</strong> — o sistema entrega um score de risco e um resumo de evidências para revisão humana, em vez de rejeitar cadastros automaticamente, mantendo uma pessoa no circuito para os casos limítrofes."],
  ["Claude Code as the primary development partner: scaffolding the pipeline architecture, iterating on the OCR validation logic, debugging embedding comparisons, and reviewing the risk-scoring model. This is consistent with my AI-first building approach — AI as co-pilot from architecture to implementation.",
   "Claude Code como parceiro principal de desenvolvimento: estruturando a arquitetura do pipeline, iterando na lógica de validação de OCR, depurando as comparações de embedding e revisando o modelo de risk scoring. Isso é coerente com a minha forma AI-first de construir — a IA como copiloto da arquitetura à implementação."],
  [">Facial recognition embeddings</span>", ">Embeddings de reconhecimento facial</span>"],
  [">Risk scoring logic</span>", ">Lógica de risk scoring</span>"],

  // ---------- case 06 round border ----------
  ["05 · LATAM Marketplace · Operations Lead", "05 · Marketplace LATAM · Líder de Operações"],
  [">Round Border — Automated Store Closures for Mass Events</div>", ">Round Border — Fechamento Automático de Lojas em Grandes Eventos</div>"],
  ["9 countries · 100% automated · 2 closure modes", "9 países · 100% automatizado · 2 modos de fechamento"],
  ["During mass events — carnival street parties, protests, large concerts, elections — the ops team had to <strong>manually identify which stores fell inside the affected area and close them individually</strong> at the right time. This was slow, error-prone, and entirely dependent on someone scanning a map and remembering to act at the exact moment the event started.",
   "Durante grandes eventos — blocos de carnaval, protestos, shows grandes, eleições — o time tinha que <strong>identificar manualmente quais lojas ficavam dentro da área afetada e fechá-las uma a uma</strong> na hora certa. Era lento, sujeito a erro e totalmente dependente de alguém olhando um mapa e lembrando de agir no exato momento em que o evento começava."],
  ["A tool that automates the entire process: input a location, define an affected area, and the system identifies and schedules closures automatically. Two modes to match real-world event shapes: <strong>radius mode</strong> for point-based events (concerts, stadiums) and <strong>line mode</strong> for linear events (parade routes, marches), each expandable by a custom distance.",
   "Uma ferramenta que automatiza o processo inteiro: você informa um local, define a área afetada e o sistema identifica e agenda os fechamentos automaticamente. Dois modos para os formatos reais de evento: <strong>modo raio</strong> para eventos pontuais (shows, estádios) e <strong>modo linha</strong> para eventos lineares (rotas de desfile, passeatas), cada um expansível por uma distância personalizada."],
  ["<strong>Scheduled closures at the exact event time</strong> — removing the ops team from having to be present at a specific hour and manually trigger anything.",
   "<strong>Fechamentos agendados para a hora exata do evento</strong> — tirando do time de operação a necessidade de estar presente num horário específico para disparar algo na mão."],
  ["<strong>Built line mode as a second iteration</strong> — after seeing that many real-world events (parades, marches) don't fit a simple radius, expanding applicability without adding complexity.",
   "<strong>Modo linha como segunda iteração</strong> — depois de ver que muitos eventos reais (desfiles, passeatas) não cabem num raio simples, ampliando a aplicabilidade sem adicionar complexidade."],
  ["<strong>Scaled across all 9 countries</strong> once validated — disruptive events (protests, holidays, elections) are a universal operational challenge, not market-specific.",
   "<strong>Escalado para os 9 países</strong> depois de validado — eventos disruptivos (protestos, feriados, eleições) são um desafio operacional universal, não específico de um mercado."],
  ["Customers didn't place orders that couldn't be fulfilled. Couriers weren't sent into unsafe areas. Stores weren't overwhelmed trying to serve demand they couldn't meet. The team no longer needed to manually monitor or intervene at the exact moment an event began.",
   "Os clientes não faziam pedidos que não podiam ser atendidos. Os entregadores não eram mandados para áreas inseguras. As lojas não ficavam sobrecarregadas tentando atender uma demanda impossível. E o time não precisava mais monitorar ou intervir na mão no exato momento em que um evento começava."],
  [">Countries using the tool</div>", ">Países usando a ferramenta</div>"],
  [">Closure modes: radius & line</div>", ">Modos de fechamento: raio & linha</div>"],
  [">Automated execution at event time</div>", ">Execução automática na hora do evento</div>"],
  // round border demo (HTML + JS)
  [">Radius Closure</div>", ">Fechamento por raio</div>"],
  [">0 stores closed</div>", ">0 lojas fechadas</div>"],
  ["'0 stores closed'", "'0 lojas fechadas'"],
  ["'Mode 1 — Radius Closure'", "'Modo 1 — Fechamento por raio'"],
  ["'Mode 2 — Line Closure'", "'Modo 2 — Fechamento por linha'"],
  ["(closed===1?' store':' stores') + ' closed'", "(closed===1?' loja fechada':' lojas fechadas')"],
  ['.25)"></div>Open', '.25)"></div>Aberta'],
  ['.25)"></div>Closed', '.25)"></div>Fechada'],

  // ---------- case 07 whatsapp ----------
  ["08 · LATAM Marketplace · Product Operations", "08 · Marketplace LATAM · Product Operations"],
  [">Store Supervisor Automation — WhatsApp Bot</div>", ">Automação de Supervisores de Loja — Bot de WhatsApp</div>"],
  ["~80% reduction in on-site supervisors · 9 countries · 0 drop in quality",
   "~80% menos supervisores presenciais · 9 países · 0 queda de qualidade"],
  ["Store supervisors across the grocery/mart operation were spending most of their time solving <strong>algorithm-driven problems</strong> — courier assignment, order cancellations, routing — rather than focusing on in-store quality. The root cause wasn't a staffing issue. It was a product gap: the work these supervisors were doing didn't require physical presence, but no system existed to let them do it remotely.",
   "Os supervisores de loja da operação de mercado/grocery passavam a maior parte do tempo resolvendo <strong>problemas gerados pelo algoritmo</strong> — atribuição de entregador, cancelamentos, roteirização — em vez de focar na qualidade dentro da loja. A causa raiz não era de pessoal. Era uma lacuna de produto: o trabalho desses supervisores não exigia presença física, mas não existia sistema que os deixasse fazer isso remotamente."],
  ["A <strong>WhatsApp-based bot</strong> where shoppers identify themselves and select their issue from a structured list. Simple cases resolve automatically; complex cases route to a remote support queue. WhatsApp was chosen because it required zero onboarding — shoppers already used it daily.",
   "Um <strong>bot no WhatsApp</strong> onde os shoppers se identificam e escolhem o problema numa lista estruturada. Casos simples se resolvem sozinhos; casos complexos vão para uma fila de suporte remoto. Escolhemos o WhatsApp porque exigia zero onboarding — os shoppers já usavam todo dia."],
  ["<strong>Single global decision tree</strong> — one structured taxonomy covering all markets, rather than bespoke flows per country.",
   "<strong>Uma única árvore de decisão global</strong> — uma taxonomia estruturada cobrindo todos os mercados, em vez de fluxos sob medida por país."],
  ["<strong>Human team for judgment-only cases</strong> — only genuinely complex issues reached a person, keeping the support team small and focused.",
   "<strong>Time humano só para casos de julgamento</strong> — só os problemas realmente complexos chegavam a uma pessoa, mantendo o time de suporte pequeno e focado."],
  ["<strong>Full interaction logging</strong> — every conversation created a data trail for tracking resolution time and identifying patterns for future automation.",
   "<strong>Log completo das interações</strong> — cada conversa gerava uma trilha de dados para acompanhar o tempo de resolução e identificar padrões para automações futuras."],
  ["Problem identification &amp; reframing (staffing → product) · End-to-end solution design &amp; issue taxonomy · Cross-functional delivery with engineering · Rollout across 9 countries.",
   "Identificação &amp; reenquadramento do problema (pessoal → produto) · Design da solução de ponta a ponta &amp; taxonomia de problemas · Entrega cross-funcional com engenharia · Rollout em 9 países."],
  [">Reduction in on-site supervisors needed</div>", ">Redução de supervisores presenciais necessários</div>"],
  [">Countries covered</div>", ">Países cobertos</div>"],
  [">Drop in in-store quality metrics</div>", ">Queda nas métricas de qualidade em loja</div>"],

  // ---------- shared metric values ----------
  [">100s of K</div>", ">centenas de mil</div>"],
  [">10s of K</div>", ">dezenas de mil</div>"],
  [">&lt;5 sec</div>", ">&lt;5 seg</div>"],
  [">3 days</div>", ">3 dias</div>"],
  [">1,700</div>", ">1.700</div>"],

  // ---------- skills ----------
  [">Tools &amp; skills</div>", ">Ferramentas &amp; habilidades</div>"],
  [">How I work</h2>", ">Como eu trabalho</h2>"],
  [">Analytics & data</div>", ">Analytics & dados</div>"],
  [">AI tools</div>", ">Ferramentas de IA</div>"],
  [">Data &amp; geospatial</div>", ">Dados &amp; geoespacial</div>"],
  [">Engineering collab</div>", ">Colaboração com engenharia</div>"],
  [">Languages</div>", ">Idiomas</div>"],
  [">Process</div>", ">Processo</div>"],
  [">Building products with AI</li>", ">Construir produtos com IA</li>"],
  [">Discovery &amp; PRD drafting</li>", ">Discovery &amp; redação de PRD</li>"],
  [">Prototyping &amp; test generation</li>", ">Prototipagem &amp; geração de testes</li>"],
  [">Jenkins (basic)</li>", ">Jenkins (básico)</li>"],
  [">🇧🇷 Portuguese — native</li>", ">🇧🇷 Português — nativo</li>"],
  [">🇪🇸 Spanish — bilingual</li>", ">🇪🇸 Espanhol — bilíngue</li>"],
  [">🇬🇧 English — professional</li>", ">🇬🇧 Inglês — profissional</li>"],
  [">Discovery &amp; roadmapping</li>", ">Discovery &amp; roadmap</li>"],
  [">Agile · sprint ceremonies</li>", ">Ágil · cerimônias de sprint</li>"],
  [">A/B testing &amp; experimentation</li>", ">Testes A/B &amp; experimentação</li>"],
  [">Cross-country launches</li>", ">Lançamentos multipaís</li>"],

  // ---------- career ----------
  [">Career path</div>", ">Trajetória</div>"],
  [">8 years at Rappi</h2>", ">8 anos de Rappi</h2>"],
  ["From field operations in Porto Alegre to product ownership across 9 countries. Every role built on the one before it.",
   "Da operação de campo em Porto Alegre à responsabilidade por produto em 9 países. Cada cargo construído em cima do anterior."],
  [">2022 – Jun 2026</div>", ">2022 – jun 2026</div>"],
  [">Nov 2018 – 2019</div>", ">nov 2018 – 2019</div>"],
  [">Apr – Nov 2018</div>", ">abr – nov 2018</div>"],
  [">Product Manager — Backoffice & Consumer</div>", ">Product Manager — Backoffice & Consumo</div>"],
  [">Operations Lead</div>", ">Líder de Operações</div>"],
  [">Regional Operations Analyst & Supervisor</div>", ">Analista e Supervisora Regional de Operações</div>"],
  [">Operations Assistant</div>", ">Assistente de Operações</div>"],
  ["Built and scaled a real-time monitoring platform across 9 LATAM countries. Owned roadmap for internal ops platforms — alerting, automation bots, monitoring dashboards. Shipped VoIP integration (Amazon Chime) to 80% of users. Built AI-powered evidence scoring for Order Not Delivered, saving $20K/month. Led cancellations UX redesign saving 1,700 orders/week.",
   "Construí e escalei uma plataforma de monitoramento em tempo real em 9 países da América Latina. Dona do roadmap das plataformas internas de operação — alertas, bots de automação, dashboards de monitoramento. Entreguei a integração VoIP (Amazon Chime) para 80% dos usuários. Criei o scoring de evidências com IA para Pedido Não Entregue, economizando US$ 20 mil/mês. Liderei o redesenho da UX de cancelamentos, salvando 1.700 pedidos/semana."],
  ["Built the Ops Control Center from scratch — reducing incident response from 1+ hour to under 5 minutes across 9 countries. Developed 50+ real-time marketplace alerts. Reduced operational headcount from 150 to 30 through automation, generating $500K/year in savings.",
   "Construí o Ops Control Center do zero — reduzindo a resposta a incidentes de mais de 1 hora para menos de 5 minutos em 9 países. Desenvolvi mais de 50 alertas de marketplace em tempo real. Reduzi o headcount operacional de 150 para 30 via automação, gerando US$ 500 mil/ano de economia."],
  ["Achieved the lowest cancellation rate among all Brazilian cities under direct management — establishing Porto Alegre as a national benchmark for live operations. Conceptualized processes later scaled to multiple Brazilian states.",
   "Alcancei a menor taxa de cancelamento entre todas as cidades brasileiras sob gestão direta — estabelecendo Porto Alegre como referência nacional em operação ao vivo. Concebi processos depois escalados para vários estados do Brasil."],
  ["Supported courier onboarding and troubleshooting. Built early analytical skills by identifying recurring courier pain points and escalating patterns to the operations team.",
   "Apoiei o cadastro e o suporte a entregadores. Desenvolvi minhas primeiras habilidades analíticas identificando dores recorrentes dos entregadores e escalando padrões para o time de operação."],

  // ---------- education ----------
  [">Academic background</h2>", ">Formação acadêmica</h2>"],
  [">Post-Graduate · Project Management, Strategy & Business</div>", ">Pós-graduação · Gestão de Projetos, Estratégia & Negócios</div>"],
  [">Master's · Ecology</div>", ">Mestrado · Ecologia</div>"],
  ["Analytical rigor, complex systems thinking, data-driven methodology.",
   "Rigor analítico, pensamento em sistemas complexos, metodologia orientada a dados."],
  [">Bachelor's · Ecology & Environmental Management</div>", ">Bacharelado · Ecologia & Gestão Ambiental</div>"],

  // ---------- contact ----------
  [">Let's talk</h2>", ">Vamos conversar</h2>"],
  ["I'm actively looking for my next PM role — remote-first, with a strong preference for products that serve real operational complexity at scale.",
   "Estou em busca ativa do meu próximo desafio como PM — remoto de preferência, com forte inclinação por produtos que lidam com complexidade operacional real, em escala."],
  ["Hotzones live demo", "Hotzones — demo ao vivo"],
  [">Availability</div>", ">Disponibilidade</div>"],
  ["</div>Open to new opportunities</div>", "</div>Aberta a novas oportunidades</div>"],
  ["</div>Remote globally</div>", "</div>Remoto globalmente</div>"],
  ["</div>Hybrid · Porto Alegre, Brazil</div>", "</div>Híbrido · Porto Alegre, Brasil</div>"],
  ["</div>Occasional travel to São Paulo</div>", "</div>Viagens ocasionais a São Paulo</div>"],
  ["</div>UTC-3 · trilingual</div>", "</div>UTC-3 · trilíngue</div>"],

  // ---------- footer + demo buttons ----------
  ["Built with HTML · Hosted on GitHub Pages", "Feito com HTML · Hospedado no GitHub Pages"],
  ["⏸ Pause", "⏸ Pausar"],
  ["▶ Play", "▶ Tocar"],
  // botão "ver mais" (HTML + textos do JS)
  [">See more projects ↓</button>", ">Ver mais projetos ↓</button>"],
  ["'See more projects ↓'", "'Ver mais projetos ↓'"],
  ["'See less ↑'", "'Ver menos ↑'"],
];

// aplica do mais longo pro mais curto, pra evitar colisões de substring
pairs.sort((a, b) => b[0].length - a[0].length);
let missing = [];
for (const [en, pt] of pairs) {
  if (!html.includes(en)) { missing.push(en); continue; }
  html = html.split(en).join(pt);
}

fs.writeFileSync("pt.html", html, "utf8");
console.log("pt.html gerado.");
if (missing.length) {
  console.log("\n⚠️  Não encontrados (revisar):");
  missing.forEach((m) => console.log("  - " + m.slice(0, 70)));
}
